name: Sync Plugins

# Trigger the workflow on pull requests and pushes to master
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'plugins.json'
  push:
    branches:
      - master
    paths:
      - 'plugins.json'

jobs:
  sync_plugins:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step to set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step to install dependencies
      - name: Install dependencies
        run: npm install

      # Step to run sync process with development environment variables on PR events
      - name: Run sync process with dev env vars
        if: github.event_name == 'pull_request'
        env:
          WEBFLOW_SYNC_AND_PUBLISH_TOKEN: ${{ secrets.WEBFLOW_SYNC_AND_PUBLISH_TOKEN_DEV }}
          WEBFLOW_PLUGINS_COLLECTION_ID: ${{ secrets.WEBFLOW_PLUGINS_COLLECTION_ID_DEV }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY_DEV }}
          ALGOLIA_APP_ID: V3VM7IN3TH
          ALGOLIA_PLUGINS_INDEX: dev_PLUGINS_SEARCH_GROWTH
        run: node sync-script.js

      # Step to run sync process with production environment variables on push to master
      - name: Run sync process with prod env vars
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          WEBFLOW_SYNC_AND_PUBLISH_TOKEN: ${{ secrets.WEBFLOW_SYNC_AND_PUBLISH_TOKEN_PROD }}
          WEBFLOW_PLUGINS_COLLECTION_ID: ${{ secrets.WEBFLOW_PLUGINS_COLLECTION_ID_PROD }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY_PROD }}
          ALGOLIA_APP_ID: V3VM7IN3TH
          ALGOLIA_PLUGINS_INDEX: prod_PLUGINS_SEARCH_GROWTH
        run: node sync-script.js
